//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: velocity_grpc.proto

package com.esri.realtime.core.grpc;

@kotlin.jvm.JvmSynthetic
inline fun feature(block: com.esri.realtime.core.grpc.FeatureKt.Dsl.() -> kotlin.Unit): com.esri.realtime.core.grpc.Feature =
  com.esri.realtime.core.grpc.FeatureKt.Dsl._create(com.esri.realtime.core.grpc.Feature.newBuilder()).apply { block() }._build()
object FeatureKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: com.esri.realtime.core.grpc.Feature.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.esri.realtime.core.grpc.Feature.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.esri.realtime.core.grpc.Feature = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class AttributesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .google.protobuf.Any attributes = 1;</code>
     */
     val attributes: com.google.protobuf.kotlin.DslList<com.google.protobuf.Any, AttributesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getAttributesList()
      )
    /**
     * <code>repeated .google.protobuf.Any attributes = 1;</code>
     * @param value The attributes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAttributes")
    fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Any, AttributesProxy>.add(value: com.google.protobuf.Any) {
      _builder.addAttributes(value)
    }/**
     * <code>repeated .google.protobuf.Any attributes = 1;</code>
     * @param value The attributes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAttributes")
    inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Any, AttributesProxy>.plusAssign(value: com.google.protobuf.Any) {
      add(value)
    }/**
     * <code>repeated .google.protobuf.Any attributes = 1;</code>
     * @param values The attributes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllAttributes")
    fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Any, AttributesProxy>.addAll(values: kotlin.collections.Iterable<com.google.protobuf.Any>) {
      _builder.addAllAttributes(values)
    }/**
     * <code>repeated .google.protobuf.Any attributes = 1;</code>
     * @param values The attributes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllAttributes")
    inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Any, AttributesProxy>.plusAssign(values: kotlin.collections.Iterable<com.google.protobuf.Any>) {
      addAll(values)
    }/**
     * <code>repeated .google.protobuf.Any attributes = 1;</code>
     * @param index The index to set the value at.
     * @param value The attributes to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setAttributes")
    operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Any, AttributesProxy>.set(index: kotlin.Int, value: com.google.protobuf.Any) {
      _builder.setAttributes(index, value)
    }/**
     * <code>repeated .google.protobuf.Any attributes = 1;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearAttributes")
    fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Any, AttributesProxy>.clear() {
      _builder.clearAttributes()
    }}
}
@kotlin.jvm.JvmSynthetic
inline fun com.esri.realtime.core.grpc.Feature.copy(block: com.esri.realtime.core.grpc.FeatureKt.Dsl.() -> kotlin.Unit): com.esri.realtime.core.grpc.Feature =
  com.esri.realtime.core.grpc.FeatureKt.Dsl._create(this.toBuilder()).apply { block() }._build()
