// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: velocity_grpc.proto

package com.esri.realtime.core.grpc;

public interface FeatureOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Feature)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .google.protobuf.Any attributes = 1;</code>
   */
  java.util.List<com.google.protobuf.Any> 
      getAttributesList();
  /**
   * <code>repeated .google.protobuf.Any attributes = 1;</code>
   */
  com.google.protobuf.Any getAttributes(int index);
  /**
   * <code>repeated .google.protobuf.Any attributes = 1;</code>
   */
  int getAttributesCount();
  /**
   * <code>repeated .google.protobuf.Any attributes = 1;</code>
   */
  java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
      getAttributesOrBuilderList();
  /**
   * <code>repeated .google.protobuf.Any attributes = 1;</code>
   */
  com.google.protobuf.AnyOrBuilder getAttributesOrBuilder(
      int index);
}
