//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: velocity_grpc.proto

package com.esri.realtime.core.grpc;

@kotlin.jvm.JvmSynthetic
inline fun request(block: com.esri.realtime.core.grpc.RequestKt.Dsl.() -> kotlin.Unit): com.esri.realtime.core.grpc.Request =
  com.esri.realtime.core.grpc.RequestKt.Dsl._create(com.esri.realtime.core.grpc.Request.newBuilder()).apply { block() }._build()
object RequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: com.esri.realtime.core.grpc.Request.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.esri.realtime.core.grpc.Request.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.esri.realtime.core.grpc.Request = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class FeaturesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .Feature features = 1;</code>
     */
     val features: com.google.protobuf.kotlin.DslList<com.esri.realtime.core.grpc.Feature, FeaturesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getFeaturesList()
      )
    /**
     * <code>repeated .Feature features = 1;</code>
     * @param value The features to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addFeatures")
    fun com.google.protobuf.kotlin.DslList<com.esri.realtime.core.grpc.Feature, FeaturesProxy>.add(value: com.esri.realtime.core.grpc.Feature) {
      _builder.addFeatures(value)
    }/**
     * <code>repeated .Feature features = 1;</code>
     * @param value The features to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignFeatures")
    inline operator fun com.google.protobuf.kotlin.DslList<com.esri.realtime.core.grpc.Feature, FeaturesProxy>.plusAssign(value: com.esri.realtime.core.grpc.Feature) {
      add(value)
    }/**
     * <code>repeated .Feature features = 1;</code>
     * @param values The features to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllFeatures")
    fun com.google.protobuf.kotlin.DslList<com.esri.realtime.core.grpc.Feature, FeaturesProxy>.addAll(values: kotlin.collections.Iterable<com.esri.realtime.core.grpc.Feature>) {
      _builder.addAllFeatures(values)
    }/**
     * <code>repeated .Feature features = 1;</code>
     * @param values The features to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllFeatures")
    inline operator fun com.google.protobuf.kotlin.DslList<com.esri.realtime.core.grpc.Feature, FeaturesProxy>.plusAssign(values: kotlin.collections.Iterable<com.esri.realtime.core.grpc.Feature>) {
      addAll(values)
    }/**
     * <code>repeated .Feature features = 1;</code>
     * @param index The index to set the value at.
     * @param value The features to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setFeatures")
    operator fun com.google.protobuf.kotlin.DslList<com.esri.realtime.core.grpc.Feature, FeaturesProxy>.set(index: kotlin.Int, value: com.esri.realtime.core.grpc.Feature) {
      _builder.setFeatures(index, value)
    }/**
     * <code>repeated .Feature features = 1;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearFeatures")
    fun com.google.protobuf.kotlin.DslList<com.esri.realtime.core.grpc.Feature, FeaturesProxy>.clear() {
      _builder.clearFeatures()
    }}
}
@kotlin.jvm.JvmSynthetic
inline fun com.esri.realtime.core.grpc.Request.copy(block: com.esri.realtime.core.grpc.RequestKt.Dsl.() -> kotlin.Unit): com.esri.realtime.core.grpc.Request =
  com.esri.realtime.core.grpc.RequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
