'''
/* Copyright 2021 Esri
 *
 * Licensed under the Apache License Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
'''

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: velocity_grpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='velocity_grpc.proto',
  package='esri.realtime.core.grpc',
  syntax='proto3',
  serialized_options=b'\n\033com.esri.realtime.core.grpcB\tGrpcProtoP\001Z\027esri/realtime/core/grpc\252\002\027Esri.Realtime.Core.Grpc',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13velocity_grpc.proto\x12\x17\x65sri.realtime.core.grpc\x1a\x19google/protobuf/any.proto\"=\n\x07Request\x12\x32\n\x08\x66\x65\x61tures\x18\x01 \x03(\x0b\x32 .esri.realtime.core.grpc.Feature\"3\n\x07\x46\x65\x61ture\x12(\n\nattributes\x18\x01 \x03(\x0b\x32\x14.google.protobuf.Any\")\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x32\xa8\x01\n\x08GrpcFeed\x12O\n\x06Stream\x12 .esri.realtime.core.grpc.Request\x1a!.esri.realtime.core.grpc.Response(\x01\x12K\n\x04Send\x12 .esri.realtime.core.grpc.Request\x1a!.esri.realtime.core.grpc.ResponseB]\n\x1b\x63om.esri.realtime.core.grpcB\tGrpcProtoP\x01Z\x17\x65sri/realtime/core/grpc\xaa\x02\x17\x45sri.Realtime.Core.Grpcb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='esri.realtime.core.grpc.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='features', full_name='esri.realtime.core.grpc.Request.features', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=136,
)


_FEATURE = _descriptor.Descriptor(
  name='Feature',
  full_name='esri.realtime.core.grpc.Feature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='attributes', full_name='esri.realtime.core.grpc.Feature.attributes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=189,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='esri.realtime.core.grpc.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='esri.realtime.core.grpc.Response.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code', full_name='esri.realtime.core.grpc.Response.code', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=232,
)

_REQUEST.fields_by_name['features'].message_type = _FEATURE
_FEATURE.fields_by_name['attributes'].message_type = google_dot_protobuf_dot_any__pb2._ANY
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Feature'] = _FEATURE
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'velocity_grpc_pb2'
  # @@protoc_insertion_point(class_scope:esri.realtime.core.grpc.Request)
  })
_sym_db.RegisterMessage(Request)

Feature = _reflection.GeneratedProtocolMessageType('Feature', (_message.Message,), {
  'DESCRIPTOR' : _FEATURE,
  '__module__' : 'velocity_grpc_pb2'
  # @@protoc_insertion_point(class_scope:esri.realtime.core.grpc.Feature)
  })
_sym_db.RegisterMessage(Feature)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'velocity_grpc_pb2'
  # @@protoc_insertion_point(class_scope:esri.realtime.core.grpc.Response)
  })
_sym_db.RegisterMessage(Response)


DESCRIPTOR._options = None

_GRPCFEED = _descriptor.ServiceDescriptor(
  name='GrpcFeed',
  full_name='esri.realtime.core.grpc.GrpcFeed',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=235,
  serialized_end=403,
  methods=[
  _descriptor.MethodDescriptor(
    name='Stream',
    full_name='esri.realtime.core.grpc.GrpcFeed.Stream',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Send',
    full_name='esri.realtime.core.grpc.GrpcFeed.Send',
    index=1,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GRPCFEED)

DESCRIPTOR.services_by_name['GrpcFeed'] = _GRPCFEED

# @@protoc_insertion_point(module_scope)
