// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: velocity_grpc.proto

package com.esri.realtime.core.grpc;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>int32 code = 2;</code>
   * @return The code.
   */
  int getCode();
}
